### ISSUE TITLE
Clear user data or cache?

### ISSUE THREAD

**Issue by jason-nabooki** [forged-ui/support#2]
I installed an early version which loaded fine but after installing 1.0.10 the app no longer opens. The icon appears in the dock and then shortly after disappears.

OSX 10.15.4 (19E287)

Is there a location where user data/cache is stored that I could try wiping ?

**Comment by jason-nabooki** [comment]
This is the output if i run from terminal

Last login: Tue Apr 14 11:49:10 on ttys001
/Applications/Forged\ UI.app/Contents/MacOS/Forged\ UI ; exit;
nb@Nb-MacBook-Pro ~ % /Applications/Forged\ UI.app/Contents/MacOS/Forged\ UI ; exit;
No pusher key specified... ignoring...
Checking for update
Update for version 1.0.11 is not available (latest version: 1.0.11, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null


Then it just sits there, doing nothing.

**Comment by OwenMelbz** [comment]
Hi Jason,

Firstly sorry about this!

What version of macOS are you running please?

I've just been doing some digging and it seems in the latest Catalina security updates requires a different method of packaging which could be related.

Would you also please be able to confirm if the tray icon in the toolbar is visible or not please? It should look something like

<img width="107" alt="Item-0_and_Item-0_and_Item-0" src="https://user-images.githubusercontent.com/1094740/79197822-53ed2c80-7e2a-11ea-91aa-74d94e11704c.png">

Thanks

**Comment by jason-nabooki** [comment]
Hi @OwenMelbz ,

I'm running OSX 10.15.4 (19E287) which I think is the latest.

Oh, haha. Yes I just noticed that icon now. If I click on that and then click "Open" the window appears. Not sure if this is expected behaviour? When I open the application I was kind of expecting to see the window.

**Comment by OwenMelbz** [comment]
Hi,

Yes it is currently the expected behaviour, it was designed in mind (as I was building originally for internal usage) for deployment notifications, so the flow was as follows:

- Open it for the first time, it will display everything to let you configure
- Start work one morning - Launch the app so its ready in the background listening for notifications
- Keep it out of the dock out of sight until it's "needed"
- Launch from the tray icon when needed - which creates the dock icon as there is now a window to focus.

This also lets us reduce memory utilisation as we can keep it warm in memory to launch the windows more quickly, along with pushing "Cmd + N" to launch multiple instances - but not running the full app keeps the footprint smaller.

--

That being said - potentially could look into making that a launch option from the preferences to say something like "Minimise on launch" so users can change that setting based off their use-cases.

Do you feel thats a suitable solution? If so I can look at having that released maybe by the end of the week

**Comment by jason-nabooki** [comment]
That all makes sense. I guess the main thing that tripped me up was when you open it, the dock icon appears, bounces, then disappears. So it seemed like the application was crashing upon startup.

I like the idea of giving the option for hide/show window at launch. For my use case I'd probably always want the window to show at launch.

**Comment by OwenMelbz** [comment]
Hi,

This has been added to 10.0.12 which should be available via the auto-updater.

![Preferences____Forge_UI_and_Clear_user_data_or_cache__·_Issue__2_·_forged-ui_support](https://user-images.githubusercontent.com/1094740/82599500-53bc1b80-9ba4-11ea-9a48-deeb9a8e03bb.jpg)
